### ISSUE TITLE
Add IMU reference frame

### ISSUE THREAD

**Issue by ayrton04** [cra-ros-pkg/robot_localization#22]
See this ROS answers question for some background:

http://answers.ros.org/question/50870/what-frame-is-sensor_msgsimuorientation-relative-to/

EDIT: Just updating this to reflect the issue as I see it now. We only have a Microstrain 3DM-GX2 in house (and we're using a [slightly modified driver](https://github.com/cra-ros-pkg/microstrain_3dmgx2_imu)), but the issue is that the absolute orientation is reported in a world-fixed frame, but the angular velocities and linear accelerations are reported in the sensor frame. Since the ROS IMU message type has only one `frame_id`, we have to be careful defining the transform from the IMU frame to the vehicle frame. Defining a transform from the vehicle body frame to the IMU frame will work for transforming the IMU's angular velocities and linear accelerations, but may not work for the absolute orientation. But:

1. What I just said could be wrong, and using the same transform on the absolute orientation may actually "undo" the sensor's mounting rotation. I just have to check the math. Transforming an orientation is not the same as transforming an angular velocity. In the latter, if you lay the IMU on its side and rotate it, you'll still see pitch velocity changing, but what you really want is yaw velocity. The way robot_localization applies the transform would handle this situation.
2. Even if it the absolute orientation is wrong, since the orientation is reported in a world-fixed frame, all the user has to do is turn on differential integration for the IMU, and this becomes a moot point.

Right now, the robot_localization will transform the IMU data - absolute orientation, angular velocity, and linear acceleration - into the frame specified by the `base_link_frame` parameter. This may be sufficient for most users' needs. I'll let this issue stand while I verify a few things, but I may end up just leaving it as-is and documenting how the package behaves when it comes to IMU transformations.

**Comment by ayrton04** [comment]
What I think I may do now - at least until the IMU message is changed or a new one is created - is add (yet another) parameter for each IMU, called imuN_world_frame_id. The assumption would be that the frame_id in the header of the IMU message would refer to the sensor frame data (angular velocity and acceleration), and the imuN_world_frame_id would refer to the orientation data.

**Comment by paulbovbel** [comment]
Are there any cases where this wouldn't already line up with the world_frame parameter?

**Comment by ayrton04** [comment]
It depends. If the IMU reports data in NED, then it will need to be transformed. If we're enforcing ENU for IMU data via the REP, then we can tell users to simply use the differential setting and I can close this. :)

**Comment by paulbovbel** [comment]
Okay, now I'm confused. 

1. So essentially the IMU world frame would be an 'orientation offset' (the physical orientation of the IMU when the output orientation is (0 0 0 1).
2. Wouldn't knowing that offset be unnecessary in differential mode, since NED and ENU are both right-handed?

**Comment by ayrton04** [comment]
Perhaps this is a case of my not having had coffee this morning, but consider the case where we have an IMU that reports orientation data in NED. This means the Z-axis points down, and the Y-axis points to the right. The IMU is mounted in its natural orientation, i.e., not rotated. As the robot turns counter-clockwise, the reported yaw decreases instead of increasing, no? If we were displaying the robot in rviz, it would appear to turn clockwise, instead of turning counter-clockwise. Using the differential parameter wouldn't help in this case, as the difference between two measurements is still going in the wrong direction. Perhaps I'm missing something, though.

**Comment by paulbovbel** [comment]
Assuming we're using an IMU that reports orientation relative to a 'true' world frame. If I take my mostly-functional Microstrain and place it in its natural orientation (upside down, serial cable pointed north). Speaking in RPY, orientation is 0, 0, 0. Turning it counter clockwise on a flat surface, yaw increases (0, 0, +), and vice versa.

If I now flip it over, manufacturer label up, serial cable still pointed north, RPY = pi, 0, 0. Because RPY is evaluated in the world frame, if I now rotate it counter clockwise on the table surface, yaw still increases (pi, 0, +), and vice versa.

I don't think I've had enough coffee to think in quaternions, but I think the same ideas apply.

**Comment by ayrton04** [comment]
Yes, that sounds correct for me, and I'm guessing your IMU reports in ENU. However, I have a VectorNav VN-100, and it reports data in NED. Here is its natural orientation:

![img_6806](https://cloud.githubusercontent.com/assets/5042191/5821543/f458a9ba-a09a-11e4-8d60-a191d767ab46.JPG)

In that orientation, if I rotate it counter-clockwise, the yaw decreases. If I flip it over so the label is facing the ground...

![img_6808](https://cloud.githubusercontent.com/assets/5042191/5821620/84c2fa6e-a09b-11e4-8e87-828e44004526.JPG)

...and then rotate it counter-clockwise, the yaw still decreases. The frame is still right-handed, but I'd have to transform the data to get it to agree with the ROS standard of the Z-axis pointing up.

**Comment by mikepurvis** [comment]
The suggestion given in the newly minted [REP-0103 update](http://www.ros.org/reps/rep-0103.html#suffix-frames) is that `base_link` and `imu_link` are both orientated the same way, but a separate `imu_link_ned` frame is defined which is over top of `imu_link` but rolled over so that the data still transforms back as expected.

The trick for this to work, of course, is that anything consuming sensor_msgs/Imu must be transforming the data back to `base_link` (or whatever) before use. That is not a realistic expectation until there is a standard transformImu function supplied in tf2_ros.

**Comment by paulbovbel** [comment]
@mikepurvis, I've started working on something to put into tf2_sensor_msgs for Imu.

@ayrton04, that's so strange, clearly my coffee is lacking. The microstrain is definitely NED. My intuition says that in the second picture of the VN-100, the orientation should read (0,0,0), and rotating clockwise should generate a positive yaw, as the z-axis is pointing up. That's typically the way VN-100 would be mounted in an aircraft, so wouldn't that be the 'natural' orientation.

**Comment by ayrton04** [comment]
I believe the disconnect is that the axes don't move with the sensor, so if I flip it over, the Z axis isn't pointing up, but remains pointing down. I'm guessing picture on the IMU shows the fixed world frame as it should be in the IMU's natural pose, but that picture is no longer valid once the IMU is in any other orientation. Instead, the coordinate frame remains fixed.

**Comment by paulbovbel** [comment]
Arg thanks, hopefully i've reconnected: If a sensor reports in NED, then orientation should be (0,0,0) in  the natural orientation, when the sensor's axes point x-north, y-east, z-down. Then the Microstrain I have is not properly reporting in NED, hence my confusion. It reports (0,0,0) in x-north, y-west, z-up.

**Comment by paulbovbel** [comment]
I'm still not 100% on why a world_frame is needed -> shouldn't the transform from NED to ENU be built into the base_link->imu_link transform that defines where on the vehicle the IMU is mounted, and how it's oriented?

**Comment by ayrton04** [comment]
My response is more thinking aloud than anything, so take it with a grain of salt.

Anyway, I need to double-check the math, but I think it depends on how you apply the transform. If your IMU's default frame is ENU, then mounting it upside-down will simply give you a roll value of 180 degrees. As you pointed out with the Microstrain IMU, the signs for the orientation variables will still increase and decrease in the correct directions. In this case, if you wanted to, you could use the base_link->imu transform to undo the 180-degree rotation, effectively just treating that as an offset. I'll refer to this as case A, because I'll have to come back to it.

Unlike the orientation data, the angular velocity and linear acceleration will require completely different treatment. If your IMU is upside-down, then its pitch and yaw velocities will have the wrong sign. You'll need to apply the base_link->imu transform to correct those signs. This is case B.

Going back to case A, there are a couple issues: first, consider the case where we have some coordinate frame that is rolled 90 degrees with respect to our odom frame (odom, in this case, is our world frame). I'll call the rotated frame odom2. We now get a yaw measurement from some sensor that measures orientation *in the odom2 frame*. In this case, let's say it's a yaw measurement. Because the odom2 frame is rolled with respect to our odom frame, that yaw measurement is transformed into a pitch measurement in the odom frame. In this case, they're both right-handed, so we can apply the transform that describes the rotation from the odom frame to the odom2 frame, and voila, the yaw becomes pitch. I'll call this case C. Note, however, that the way I'd apply this transform is not the same as in case A. In case A, we're effectively adding offsets. In case C, we're actually transforming the measurements into a different coordinate frame.

Now we repeat case C, but rotate it 180 degrees instead of 90. This is equivalent to the NED frame. As with case C, we'll have to transform the data to get it into our odom frame. In this case, we'd want the signs of yaw and pitch to be reversed. 

I guess what I'm getting at is that if we have an IMU that reports in ENU, and we mount it with some rotational offset on our robot, then transforming that data is a simple matter of applying offsets. If the IMU reports data in NED (or is in NED *and* is rotated), then I'm not yet convinced that (A) the way we'd apply that transform would be the same, and (B) that the same transform would work for the IMU's sensor frame as for the IMU's world frame. 

@mikepurvis: yeah, having that REP definitely helps here, as I could then tackle this in two stages: first, go from imu_ned to imu, which would transform the data into ENU by applying the transform as I would in case (C). I then can add the rotational offsets as in case (A). 

Again, sorry for the tome. :)

**Comment by paulbovbel** [comment]
Your tome is greatly appreciated. I think part of the problem in getting my ahead around this may be that I don't have any devices that behave properly in enu OR ned. However, 2 things:

1) As far as I understand, the only difference between an ENU and NED device is, which orientation that device reports as its 'natural orientation' - (0,0,0), which is the orientation of its world frame.
2) In terms of rotations, applying an offset the same thing as transforming the coordinate frame. Either one is just multiplying by the appropriate quaternion, which is a reversible operation. These operations are also stackable, though not commutative.
3) Therefore the ENU or NED reference should be encapsulated in the base_link to imu_link transform.
4) If the goal is to calculate the transformation between world_frame and base_link, and world_frame to imu_link is specified as a right-handed transform/orientation by the IMU, then base_link to imu_link transform is the only missing piece of information that needs to be specified by the user.

I'm going to get my microstrain to work as a proper ENU and NED device (given a parameter) tomorrow. Looks like a fork of the driver is appropriate for the 3dm-gx3-25.

**Comment by ayrton04** [comment]
Sorry, been buried for a couple days.

I think the struggle I'm having is with your statements in (1) and (2). If I'm following what you're saying, you're arguing that an ENU IMU that is flipped over is therefore equivalent to an NED sensor (forgive me if I'm misinterpreting). 

An ENU IMU, when rolled over, would read 180 degrees of roll. If you then rotated it counter-clockwise, it would still read +yaw. An NED sensor would read -yaw. I'll pose this question: what transform would you apply to an ENU IMU that is mounted upside-down, so that it reports 0 degrees of roll, instead of 180? Then, what transform would you apply to the NED IMU to make it equivalent to the ENU IMU? I don't think those transforms are the same, and there's the problem.

I need to put together some tf tests and also compare the behavior of my ENU-converted Microstrain against my NED VectorNav. I'll post them when I get through them.

Also, forgive me if I'm being dense. My concerns regarding this are obviously w.r.t. robot_localization and avoiding ambiguity in sensor data, so I want to be certain.

**Comment by paulbovbel** [comment]
I'm struggling to get my head around all this stuff, so believe me I feel very dense. I'm not 100% on my quaternion math, but this appears to work (https://github.com/ros/geometry_experimental/pull/78).

Specifically if I publish NED data in imu_link_ned, and then create the transform where ENU -> NED is RPY(pi, 0, pi/2):
  <node pkg="tf" type="static_transform_publisher" name="tf_imu_ned"
        args="0 0 0 1.5708 0 3.1416 imu_link imu_link_ned 10" output="screen"/>

I can then use the transform in the pull on the NED message to get (as far as I can tell) proper ENU data.
---
However, after playing around with IMU filter madgwick, I've realised that you're very right, a global context frame, or an ENU assumption is necessary. This filter generates the imu.orientation component from imu.angular_velocity and imu.linear_acceleration. Since an IMU message contains no world reference, this filter fails for NED data because it assumes that the sensor's acceleration vector points along +ve z. Since for NED the acceleration is negative along the z-axis, the filter calculates the IMU as being upside down.

Lacking the ability to change the message, it may be reasonable for a node (e.g. filter madgwick, robot_localization), to specify that incoming data should be ENU, assuming a transforming node(let) is provided within ROS.Maybe that would fit into http://wiki.ros.org/imu_pipeline or something similar.

**Comment by tonybaltovski** [comment]
@ayrton04 the transform from NED to ENU is:
body-fixed (acc, gyro) NED -> ROS ENU: (x y z) -> (x -y -z) or (w x y z) -> (x -y -z w)
world NED (mag) -> ROS ENU: (x y z) -> (y x -z) or (w x y z) -> (y x -z w)
I believe, flipping (roll 180) the IMU would just be:
body-fixed (x -y -z) (the same ned)
world (y+pi x -z) 
but it is always the mag that I have the issues with transforming so that may need work.  Hopefully, this  helps.

**Comment by ayrton04** [comment]
Sorry, I fell off the face of the earth again.

@paulbovbel Thanks again for all your time looking into this! I think your idea of simply specifying an ENU requirement for IMU data is great, and I plan to do that. :)

@tonybaltovski Thanks very much!

One thing is certain: I won't be working for an IMU manufacturer anytime soon. Thanks again, all. I think what I plan to do for now is enforce an ENU standard for IMU data, and then I can use the base_link->imu transform to correct orientations, angular velocities, and linear accelerations.

**Comment by paulbovbel** [comment]
Thank YOU for the lively discussion, hopefully everything shakes out okay. FYI I've added a template for NED to ENU conversion in https://github.com/ros-perception/imu_pipeline/blob/metapackage-refactor/imu_transformer/launch/ned_to_enu.launch.

**Comment by mikel-zhobro** [comment]
Hi @ayrton04, I entered the IMU's unsecurity loop-hole at last. 
The solution with using offsets to Interprate the IMU measurements 
> if you wanted to, you could use the base_link->imu transform to undo the 180-degree rotation, effectively just treating that as 
an offset. I'll refer to this as case A, because I'll have to come back to it.

is a little weird as they are not really transformations. After writing it down on paper it looks like we could avoid using offsets in general and rely only on transformations. Below I describe my line of thought. Please let me know if you want the comment refractored in an other way.


In the following I mostly refer to IMUs equiped with magnetometer and accelerometer, which I will call _fully equiped_. If one of the both sensors would miss, the orientations presented by IMU would have as reference some power-on initial coordinate system which we may or may not make use of, as the orientation would then be estimated only from the angular velocities which we (could) fuse directly.


As I understand, _fully equiped_ IMUs give out orientations referenced to a world fixed frame. In most scenarious these world fixed frames are ENU(x-east, y-north and z-up) or NED( x-north, y-east, z-down). Both coordinate frames are formed from a plane tangent to the Earth's surface. As shown in the photo below taken from [wikipedia](https://en.wikipedia.org/wiki/Local_tangent_plane_coordinates).
![ECEF_ENU_Longitude_Latitude_relationships](https://user-images.githubusercontent.com/25222253/96565756-11b71300-12c5-11eb-9f07-b41939cebd6b.png)

We care only for the orientation of the ENU(NED) coordinate system not for its origin as we deal only with rotations. 

The situation is the following:
1. We get orientations of the IMU sensor in the world fixed frame (roll_ENU, pitch_ENU, yaw_ENU) of the IMU sensor -> **R_enu_imu_meas**
2. We know how the IMU sensor is oriented in our vehicle and we have an estimate of it from our map frame ->  **R_map_imu = R_map_bl * R_bl_imu**
3. We want to know how to transform these ENU referenced orientation measurements to our map frame -> **R_map_imu_meas**
4. Afterwards we just need to make up for the orientation of the IMU on the vehicle -> **R_map_bl_new = R_map_imu_meas * R_bl_imu^-1**


![image](https://user-images.githubusercontent.com/25222253/96565813-24314c80-12c5-11eb-884b-b76c53fd514a.png)


The only difficulty in all of this is how to get **R_map_enu** transformation which would allow as to express the measurements in map frame as: **R_map_imu_meas = R_map_enu * R_enu_imu_meas**.

There are 2 possible solutions for that:
1. We provide the Power-On Orientation of the Vehicle in ENU coordinates so -> **R_map_imu = R_enu_imu**
2. We make use of the first(or average of N first) IMU measurement to calculate **R_map_enu = R_map_bl * R_bl_imu * R_enu_imu^-1**. And than use that to transform the future measurements. This method has the other advantage that it can be used for arbitrary world fixed reference too. Maybe even for the case where the IMU is not _fully equiped_. But it comes with a bias depending on how bad our orientation estimation **R_map_bl** is at that time.
3. Finally we fuse **R_map_bl_meas = R_map_enu * R_enu_imu_meas * R_bl_imu^-1**

**Comment by ayrton04** [comment]
Sorry, not ignoring this, but I haven't had the cycles to read over it. Will get to it when I can.

**Comment by ayrton04** [comment]
So first, thank you for the write-up. I haven't read back through this thread, as it's very old, and the code base will have changed a lot since this ticket was written.

Are you proposing a change to the package? Is there a use case that you are trying to solve that the package doesn't support?
