### ISSUE TITLE
Bug report. NAV module always prompt "Could not obtain transform from odom->baselink"

### ISSUE THREAD

**Issue by asimay** [cra-ros-pkg/robot_localization#305]
this error is always occurs when all node is launch from launch files.
error prompt as below screenshot :
![transformerr](https://cloud.githubusercontent.com/assets/8703449/18704120/3751e04a-801b-11e6-9a01-811b3a0c38fa.png)

check the reason, in line 1678：
https://github.com/cra-ros-pkg/robot_localization/blob/kinetic-devel/src/ros_filter.cpp#L1678
missing duration time, add timeout to block until find latest  available transform.
will  test and commit later.
Thanks!

**Comment by ayrton04** [comment]
This isn't a bug. That transform isn't available immediately when the robot starts, because the _odom_->_base_link_ EKF hasn't started producing an estimate yet. As soon as it starts, the error goes away. If you place a blocking timeout in there, then there's a chance that you could be delaying the filter output, which I don't want to do.

I'd rather change the condition by which the error message is produced, e.g., using `ROS_ERROR_STREAM_DELAY`. This will cause the issue to only be reported after some number of seconds.

**Comment by asimay** [comment]
ok. I check document here:
http://wiki.ros.org/tf2/Tutorials/tf2%20and%20time%20%28C%2B%2B%29

The lookupTransform() takes four arguments. The 4th is an optional timeout. It will block for up to that duration waiting for it to timeout.
So **lookupTransform() will actually block until the transform between the two turtles becomes available** (this will usually take a few milliseconds), OR --if the transform does not become available-- until the timeout has been reached.

I guess this will be effect.

**Comment by ayrton04** [comment]
I'm aware of how the fourth argument behaves. The argument is always present, and uses a default value when not specified. What I am saying is that I want to keep the default, and do not wish to change the behavior of that line of code.

The real issue is that I am printing out the error too quickly.

**Comment by asimay** [comment]
OK. Thanks. Got it.
