### ISSUE TITLE
IMU Bias

### ISSUE THREAD

**Issue by caiofis** [cra-ros-pkg/robot_localization#406]
Hello, is there any way to removing the IMU bias during the fusion?

**Comment by skohlbr** [comment]
Not yet AFAIK, a feature request with some discussion can be found in #249.

**Comment by ayrton04** [comment]
No, not at present, though as @skohlbr pointed out, there is a ticket for it.

The main reason this has not been implemented yet is simply time. Rolling the bias estimation into the filter itself is going to be a challenge, because we can support an arbitrary number of IMUs, which would mean we'd have to have dynamically sized states. It's a fairly major undertaking, and while I'd be more than happy to accept a PR to this effect, my work schedule makes it difficult to implement some of these more fundamental changes.
