### ISSUE TITLE
Make UTM frame name parametric

### ISSUE THREAD

**Issue by ardabbour** [cra-ros-pkg/robot_localization#698]
#### Feature description
The `navsat_transform_node` TF child (or parent) `frame_id` is currently hardcoded -- this could be easily be made parametric; the usecase I have at hand is related to testing the performance of different localization pipelines right up to the UTM frame:
- tf tree 1 root is utm1,
- tf tree 2 root is utm2,
- tf tree 3 root is utm3,
- etc...

##### things to keep in mind:
- by default should still refer to "utm" or "local_enu" depending on `use_local_cartesian`
- should be added to the documentation

##### pros:
- more control over `navsat_transform_node`

##### cons:
- none that I could think of

**Comment by Arjan-TNO** [comment]
Or.... add the zone-name to the utm frame-name such as `utm30s` or `utm29n`.

Assume a hypothetical map with origin (lat,lon)=(0,0), which is in zone 31n. Ideally, you would setup a transform from `utm-->local_map` using this 31n zone.

It is possible that the robot/vehicle is initialized in 4 different quadrants of the map, representing 4 different UTM-zones. Assume the vehicle is in the 4th quadrant (utm zone 31s). The `navsat_transform` will setup `utm-->robot/map`, using the `31s` frame instead of the `31n` in which the `local_map` was setup.

When using the (full) utm-zone naming, the `local_map` could already broadcast all of the utm-frames that it spans (in case of the above example: 30n, 30s, 31n, 31s) as its tf-children. The `navsat_transform` node will broadcast the tf from `robot/map` to whatever utm-zone in which it was initialized, using the `utmXXy`-frame as the parent-frame.

An alternative for the map-tf broadcaster would be to wait until the `fromLL`-service is ready. Request the map_points of the local_map-reference, using the `fromLL`-service and setup a transform from the local-map origin to whatever utm-frame in which the vehicle was started.

**Comment by Timple** [comment]
I like the zone-name in the utm frame.

It's actually on our long-term todo list. Idea was to spawn TF's for all neighboring UTM zones. Let's say within a 100km reach or something.
