### ISSUE TITLE
Absolute or cartesian coordinate for odometry, and IMU Orientation

### ISSUE THREAD

**Issue by ChehabiMed** [cra-ros-pkg/robot_localization#865]
Hello, 
-i am publishing my odometry msgs in Cartesian space, do EKF expect polar or absolute coordinates? because i see some people publishing polar coordinates, and others publishing absolute coordinates!
-How can i make my ekf take in consideration the orientation of the robot, I'm using an oriented measurements for roll,pitch and yaw.
Thank you
![Screenshot from 2024-02-09 10-36-21](https://github.com/cra-ros-pkg/robot_localization/assets/102763325/fecc08fc-28bb-4059-9d47-208af5f424b3)
![Screenshot from 2024-02-09 10-35-22](https://github.com/cra-ros-pkg/robot_localization/assets/102763325/68f4282d-de04-4c71-94be-3aee36ccd0f4)

**Comment by ayrton04** [comment]
As the issue template says, please direct questions to robotics.stackexchange.com. If you have already asked a question there, please be patient and I will get to it when I can.

Also, please use text instead of screenshots. Make sure to include your full config and a sample message from all sensor inputs.
